<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="MacBook-Pro-de-Juan.local" failures="1" tests="1" name="Positive Login Test 2" time="30.823" errors="0" timestamp="23 jul. 2022 07:09:42 GMT">
  <testcase classname="ios.tests.IOSLoginTests" name="positiveLogin2" time="12.129">
    <failure type="java.lang.AssertionError" message="expected [HELLO] but found [Hello]">
      <![CDATA[java.lang.AssertionError: expected [HELLO] but found [Hello]
at ios.tests.IOSLoginTests.positiveLogin2(IOSLoginTests.java:66)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- positiveLogin2 -->
  <testcase classname="ios.tests.IOSLoginTests" name="negativeLoginWithInvalidCredentials" time="0.0">
    <ignored/>
  </testcase> <!-- negativeLoginWithInvalidCredentials -->
  <testcase classname="ios.tests.IOSLoginTests" name="positiveLogin" time="0.0">
    <ignored/>
  </testcase> <!-- positiveLogin -->
  <testcase classname="ios.tests.IOSLoginTests" name="negativeLoginErrors" time="0.0">
    <ignored/>
  </testcase> <!-- negativeLoginErrors -->
</testsuite> <!-- Positive Login Test 2 -->
